Vehicle-Management-Task-main/account/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    
    path('super_admin/', views.super_admin_page, name='super_admin_page'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('user_page/', views.user_page, name='user_page'),
]

Vehicle-Management-Task-main/main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('account.urls')),
    path('vehicle', include('vehicle.urls')),
]

Vehicle-Management-Task-main/vehicle/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth


app_name = 'vehicle'


urlpatterns = [

    path('create', views.create, name='create'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

Vehicle-Management-Task-main/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    is_super_admin = models.BooleanField('Super Admin', default=False)
    is_admin = models.BooleanField('Admin', default=False)
    is_user = models.BooleanField('User', default=False)

    

Vehicle-Management-Task-main/vehicle/models.py
from django.db import models


VEHICLE_TYPES = [
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
]

class VehicleModel(models.Model):
    vehicle_number = models.CharField(max_length=20)
    vehicle_type = models.CharField(
        max_length = 20, 
        choices=VEHICLE_TYPES, 
        default='2'
        )
    vehicle_model = models.CharField(max_length=100)
    vehicle_description = models.TextField()

Vehicle-Management-Task-main/account/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm



class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = models.User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
            'is_super_admin',
            'is_admin',
            'is_user',
        ]

Vehicle-Management-Task-main/vehicle/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class VehicleForm(forms.ModelForm):
    class Meta:
        model = models.VehicleModel
        fields = '__all__'

Vehicle-Management-Task-main/account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.views.decorators.cache import never_cache
from vehicle import models
from django.views.decorators.csrf import ensure_csrf_cookie


from . import forms


def index(request):
    return render(request, 'multi_user/index.html')


@ensure_csrf_cookie
def register(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account Created for ' + user)
            return redirect('login_user')

        else:
            messages.error(request, 'Invalid Credentials')
    else:
        form = forms.SignUpForm()

    context = {'form': form}
    return render(request, 'multi_user/register.html', context)


@never_cache
def login_user(request):
    form = forms.LoginForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None and user.is_super_admin:
                login(request, user)
                return redirect('super_admin_page')

            elif user is not None and user.is_admin:
                login(request, user)
                return redirect('admin_page')

            elif user is not None and user.is_user:
                login(request, user)
                return redirect('user_page')

            else:
                messages.info(request, 'Username or Password is incorrect')

    context = {'form': form}
    return render(request, 'multi_user/login.html', context)


@login_required(login_url='login_user')
def super_admin_page(request):
    context = {}
    context['dataset'] = models.VehicleModel.objects.all()
    return render(request, 'multi_user/super_admin_page.html', context)


@login_required(login_url='login_user')
def admin_page(request):
    context =  {}
    context['dataset'] = models.VehicleModel.objects.all()
    return render(request, 'multi_user/admin_page.html', context)


@login_required(login_url='login_user')
def user_page(request):
    context =  {}
    context['dataset'] = models.VehicleModel.objects.all()
    return render(request, 'multi_user/user_page.html', context)


def logout_user(request):
    logout(request)
    messages.success(request, 'Logged out successfully')
    return redirect('login_user')

Vehicle-Management-Task-main/vehicle/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

from . import models, forms



@login_required(login_url='login_user')
def create(request):
    context = {}
    form = forms.VehicleForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        form.save()
        messages.success(request, 'Vehicle Details Created Successfully')
        return redirect('super_admin_page')
    
    context['form'] = form
    return render(request, "CRUD/create.html", context)


@login_required(login_url='login_user')
def update(request, id):
    context = {}
    
    obj = get_object_or_404(models.VehicleModel, id=id)
    form = forms.VehicleForm(request.POST or None, instance=obj)
    
    if form.is_valid():
        messages.success(request, 'Vehicle Details Updated Successfully')
        form.save()
    
    context['form'] = form
    return render(request, "CRUD/update.html", context)


@login_required(login_url='login_user')
def delete(request, id):
    context = {}
    obj = get_object_or_404(models.VehicleModel, id=id)
    
    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Vehicle Details Deleted Successfully')
        return redirect('super_admin_page')
    
    return render(request, 'CRUD/delete.html', context)

Vehicle-Management-Task-main/templates/CRUD/create.html
{% include 'base.html'%}
{% load crispy_forms_tags %}


{% block content %}


<div class="container contact-form">
  <div class="form-group">
    <form method="post">
      <h3>Add New Details</h3>
            {% csrf_token %}
            <div class="row">
              <div class="col-12">
                {{form|crispy}}

            
            <button type="submit" class="btn btn-primary">Submit</button>
              
            <a href="{% url 'super_admin_page' %}" class="btn btn-success">Go Back <i class="fa-solid fa-circle-left"></i></a>
            </div>
    </form>
</div>

{% endblock %}

Vehicle-Management-Task-main/templates/CRUD/delete.html
{% include 'base.html'%}
{% load crispy_forms_tags %}

{% block content %}


<div class="card text-center">
    <div class="card-header">
    </div>
    <div class="card-body">
        
        <form method="POST">
            {% csrf_token %}
      <h5 class="card-title">Delete Details</h5>
      <p class="card-text">Do you want to delete this item?</p>
      <br>

      <input type="submit" class="btn btn-danger btn-lg " value="Yes" />
            
      <a href="{% url 'super_admin_page' %}" class="btn btn-success btn-lg "">No</a>
      </div>
  </div>


{% endblock %}

Vehicle-Management-Task-main/templates/CRUD/update.html
{% include 'base.html'%}
{% load crispy_forms_tags %}


{% block content %}


<div class="container contact-form">
    <div class="form-group">
    <form method="post">
      <h3>Update Details</h3>
        {% csrf_token %}
        <div class="row">
          <div class="col-12">
            {{form|crispy}}
    
        
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}	

      <br>
            <button type="submit" class="btn btn-primary">Submit</button>
              
            {% if request.user.is_super_admin %}
            <a href="{% url 'super_admin_page' %}" class="btn btn-success">Go Back <i class="fa-solid fa-circle-left"></i></a>
            {% elif request.user.is_admin %}
            <a href="{% url 'admin_page' %}" class="btn btn-success">Go Back <i class="fa-solid fa-circle-left"></i></a>
            {% endif %}
            </div>
    </form>
</div>

{% endblock %}

Vehicle-Management-Task-main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Vehicle Management System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
      <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

    <style>
        body{
            background: -webkit-linear-gradient(left, #0072ff, #00c6ff);
        }
        .contact-form{
            background: #fff;
            margin-top: 0%;
            margin-bottom: 5%;
            width: 70%;
        }
        .contact-form .form-control{
            border-radius:1rem;
        }
        .contact-image{
            text-align: center;
        }
        .contact-image img{
            border-radius: 6rem;
            width: 11%;
            margin-top: -3%;
            transform: rotate(29deg);
        }
        .contact-form form{
            padding: 14%;
        }
        .contact-form form .row{
            margin-bottom: 20%;
        }
        .contact-form h3{
            margin-bottom: 8%;
            margin-top: -13%;
            text-align: center;
            color: #0062cc;
        }
        .contact-form .btnContact {
            width: 50%;
            border: none;
            border-radius: 1rem;
            padding: 1.5%;
            background: #dc3545;
            font-weight: 600;
            color: #fff;
            cursor: pointer;
        }
        .btnContactSubmit
        {
            width: 50%;
            border-radius: 1rem;
            padding: 1.5%;
            color: #fff;
            background-color: #0062cc;
            border: none;
            cursor: pointer;
        }

    </style>
</head>
<body>
	{%  include 'navbar.html' %}
	<div class="container-fluid">
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-8">
                <hr class="mt-0 mb-4">
              </div>
            </div>
          </div>
	{% block content %}

	{% endblock %}
    </div>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

Vehicle-Management-Task-main/templates/multi_user/admin_page.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <title>Admin page</title>
</head>
{%  include 'base.html' %}

<body>
    <div class="col-md-12">
        <div class="card card-body">
            
            <table class="table table-sm">
                <tr>
                    <th>Vehicle Number</th>  
                    <th>Vehicle Type</th>  
                    <th>Model</th>  
                    <th>Desription</th>  
                    <th>Update</th>
                </tr>
    
                {% for data in dataset %}  
                <tr>  
                    <td>{{ data.vehicle_number }}</td>  
                    <td>{{ data.vehicle_type }}</td>  
                    <td>{{ data.vehicle_model }}</td>  
                    <td>{{ data.vehicle_description }}</td>  
    
                        <td><a class="btn btn-sm btn-info" href="{% url 'vehicle:update' data.id %}">Edit <i class="fas fa-edit"></i></a></td>
    
                    </tr>
                {% endfor %}
    
        
            </table>
        </div>
    </div>
    
    </div>
    

</body>
</html>

Vehicle-Management-Task-main/templates/multi_user/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN <i class="fa-regular fa-right-to-bracket"></i></h3>
				</div>
				<div class="d-flex justify-content-center form_container">
          <form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

        {% if messages %}
          <div id="messages">
            {% for message in messages %}
              {{ message }}
            {% endfor %}
          </div>
        {% endif %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account?  <a href="{% url 'register' %}" class=" mb-3 bg-danger text-white"> <u>Sign Up</u></a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

Vehicle-Management-Task-main/templates/multi_user/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		@media (min-width: 1025px) {
			.h-custom {
			height: 100vh !important;
			}
			}
	</style>

</head>
<body>
	<section class="h-100 h-custom" style="background-color: #8fc4b7;">
		<div class="container py-5 h-100">
		  <div class="row d-flex justify-content-center align-items-center h-100">
			<div class="col-lg-8 col-xl-6">
			  <div class="card rounded-3">
			
				<div class="card-body p-4 p-md-5">
				  <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Registration Info</h3>
				  <form action="{% url 'register' %}" method="POST">
					{% csrf_token %}

					{% for field in form %}

						<b>{{ field.label }}</b>
						{{ field }}
						
						<br>
						{% if field.errors %}
							<div class="alert alert-danger" role="alert">
								{{ field.errors }}
								Password shoud be a combination of minimum one Capital letter, number, Special character etc.
							</div>
						{% endif %}

					{% endfor %}


					<div class="d-flex justify-content-center mt-2 login_container">
						 <input class="btn btn-sm btn-primary" type="submit" value="Register Account">
					   </div>
				</form>
			
			<br>
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-danger" role="alert">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}	
	
			<div class="mt-2">
				<div class="d-flex justify-content-center links">
					Already have an account? <a href="{% url 'login_user' %}" class=" bg-danger text-white"> <u> Login</u></a>
				</div>
			</div>

		</div>
</section>
	<script>
		//Query All input fields
		var form_fields = document.getElementsByTagName('input')


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

Vehicle-Management-Task-main/templates/multi_user/register_2.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

                    <form action="{% url 'register' %}" method="POST">

                        {% csrf_token %}

                        {% for field in form %}

                            {{ field.label }}
                            {{ field }}
							
							<br>
							{% if field.errors %}
								<div class="alert alert-danger" role="alert">
									{{ field.errors }}
									Password shoud be a combination of minimum one Capital letter, number, Special character etc.
								</div>
							{% endif %}

						{% endfor %}


				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
				
				<br>
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-danger" role="alert">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}	
		
				<div class="mt-2">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login_user' %}" class=" bg-danger text-white"> <u> Login</u></a>
					</div>
				</div>


			</div>
		</div>
	</div>
	<script>
		//Query All input fields
		var form_fields = document.getElementsByTagName('input')


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

Vehicle-Management-Task-main/templates/multi_user/super_admin_page.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <title>Super Admin page</title>
</head>
{%  include 'base.html' %}

<body>
    <div class="col-md-11">
        <a class="btn btn-success btn-lg btn-block" href="{% url 'vehicle:create' %}"><b>Click here to Add New Vehicle Details </b> <i class="fa-solid fa-plus"></i></a></td>
        <br>
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}	

        <div class="card card-body">
            
            <table class="table table-sm">
                <tr>
                    <th>Vehicle Number</th>  
                    <th>Vehicle Type</th>  
                    <th>Model</th>  
                    <th>Desription</th>  
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
    
                {% for data in dataset %}  
                <tr>  
                    <td>{{ data.vehicle_number }}</td>  
                    <td>{{ data.vehicle_type }}</td>  
                    <td>{{ data.vehicle_model }}</td>  
                    <td>{{ data.vehicle_description }}</td>  
                    
                        <td><a class="btn btn-sm btn-info" href="{% url 'vehicle:update' data.id %}">Edit <i class="fas fa-edit"></i></a></td>
    
                        <td><a class="btn btn-sm btn-danger" href="{% url 'vehicle:delete' data.id %}">Delete <i class="fa-solid fa-trash"></i></a></td>
    
                    </tr>
                {% endfor %}
    
        
            </table>
        </div>
    </div>
    
    </div>


</body>
</html>

Vehicle-Management-Task-main/templates/multi_user/user_page.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <title>Super Admin page</title>
</head>
{%  include 'base.html' %}

<body>
    <div class="col-md-11">

        <div class="card card-body">
            
            <table class="table table-sm">
                <tr>
                    <th>Vehicle Number</th>  
                    <th>Vehicle Type</th>  
                    <th>Model</th>  
                    <th>Desription</th>  
                </tr>
    
                {% for data in dataset %}  
                <tr>  
                    <td>{{ data.vehicle_number }}</td>  
                    <td>{{ data.vehicle_type }}</td>  
                    <td>{{ data.vehicle_model }}</td>  
                    <td>{{ data.vehicle_description }}</td>  
    
                    </tr>
                {% endfor %}
    
        
            </table>
        </div>
    </div>
    
    </div>


</body>
</html>

Vehicle-Management-Task-main/templates/navbar.html
{% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if request.user.is_super_admin %}
            <h1> <a href= "{% url 'super_admin_page' %}"> <i class="fa-solid fa-user-shield"> </i> Super Admin</i></a></h1>

        {% elif request.user.is_admin %}
            <h1> <a href= "{% url 'admin_page' %}"> <i class="fa-solid fa-user-pen"></i> Admin</a></h1>

        {% elif request.user.is_user %}
            <h1><i class="fa-solid fa-user"></i> User</h1>

        {% else %}
            <h1>Not Logged In</h1>

      {% endif %}
    
    </ul>
  </div>

  {% if request.user.is_authenticated %}
    <div class="hello-msg">Hello, {{ request.user.username }}</div>
    <a class="btn btn-primary" href="{% url 'logout' %}">Logout <i class="fa-regular fa-right-from-bracket"></i></a>
  {% endif %}

</nav>